### ISSUE TITLE
Do you try this model peptide–protein interaction prediction?

### ISSUE THREAD

**Issue by rocke2020** [xueleecs/SDNN-PPI#1]
Hi Li Xue,

thanks for your share of codes!
Do you try this model peptide–protein interaction prediction?

**Comment by xueleecs** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi Rocke,Although I did not test the model on peptide-protein interactions, I think the model is also feasible for this task because peptides and proteins are made of amino acids and can be encoded into vectors for interaction prediction.Good luck with your research and have a great weekend
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 8/18/2022 16:13，Rocke ***@***.***> wrote： 




Hi Li Xue,

thanks for your share of codes!

Do you try this model peptide–protein interaction prediction?

**Comment by xueleecs** [comment]
Hi Rocke, although I did not test this model on peptide-protein interactions, I think this model is also feasible for this task because peptides and proteins are both composed of amino acids and can be encoded into vectors for interaction prediction in the same way. 
Good luck with your research and have a great weekend.
